// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for CTA documents */
interface CtaDocumentData {
    /**
     * Text field in *CTA*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cta.text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
    /**
     * URL field in *CTA*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: cta.url
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    url: prismicT.LinkField;
    /**
     * Type field in *CTA*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: cta.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    type: prismicT.SelectField<"main" | "secondary">;
}
/**
 * CTA document from Prismic
 *
 * - **API ID**: `cta`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CtaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CtaDocumentData>, "cta", Lang>;
/** Content for HomePage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *HomePage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *HomePage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = BlogSlice | FooterSlice | HeaderSlice | HeroSlice | TestimonialsSlice | NavSlice | MapSlice;
/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for MapItem documents */
interface MapitemDocumentData {
    /**
     * Title field in *MapItem*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: mapitem.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * List field in *MapItem*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: mapitem.list[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    list: prismicT.GroupField<Simplify<MapitemDocumentDataListItem>>;
}
/**
 * Item in MapItem → List
 *
 */
export interface MapitemDocumentDataListItem {
    /**
     * CTA field in *MapItem → List*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: mapitem.list[].cta
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta: prismicT.RelationField<"cta">;
    /**
     * Link field in *MapItem → List*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: mapitem.list[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link: prismicT.RichTextField;
}
/**
 * MapItem document from Prismic
 *
 * - **API ID**: `mapitem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MapitemDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<MapitemDocumentData>, "mapitem", Lang>;
/** Content for NavItem documents */
interface NavitemDocumentData {
    /**
     * Title field in *NavItem*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navitem.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * SubItem field in *NavItem*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navitem.subitem[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    subitem: prismicT.GroupField<Simplify<NavitemDocumentDataSubitemItem>>;
}
/**
 * Item in NavItem → SubItem
 *
 */
export interface NavitemDocumentDataSubitemItem {
    /**
     * Content field in *NavItem → SubItem*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: navitem.subitem[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    content: prismicT.RelationField<"post" | "testimonial">;
}
/**
 * NavItem document from Prismic
 *
 * - **API ID**: `navitem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavitemDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NavitemDocumentData>, "navitem", Lang>;
/** Content for Post documents */
interface PostDocumentData {
    /**
     * Icon field in *Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: post.icon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
    /**
     * Title field in *Post*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: post.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Body field in *Post*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post.body
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
    /**
     * List field in *Post*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: post.list
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    list: prismicT.RichTextField;
    /**
     * Image field in *Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: post.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * CTA field in *Post*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: post.cta
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta: prismicT.RelationField<"cta">;
}
/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;
/** Content for Testimonial documents */
interface TestimonialDocumentData {
    /**
     * Body field in *Testimonial*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonial.body
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
    /**
     * User name field in *Testimonial*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonial.user_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    user_name: prismicT.RichTextField;
    /**
     * User job field in *Testimonial*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonial.user_job
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    user_job: prismicT.RichTextField;
    /**
     * User location field in *Testimonial*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonial.user_location
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    user_location: prismicT.RichTextField;
    /**
     * User image field in *Testimonial*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonial.user_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    user_image: prismicT.ImageField<never>;
    /**
     * User signature field in *Testimonial*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonial.user_signature
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    user_signature: prismicT.ImageField<never>;
}
/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<TestimonialDocumentData>, "testimonial", Lang>;
export type AllDocumentTypes = CtaDocument | HomepageDocument | MapitemDocument | NavitemDocument | PostDocument | TestimonialDocument;
/**
 * Primary content in Blog → Primary
 *
 */
interface BlogSliceDefaultPrimary {
    /**
     * Title field in *Blog → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Blog → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.TitleField;
    /**
     * Body field in *Blog → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * Item in Blog → Items
 *
 */
export interface BlogSliceDefaultItem {
    /**
     * post field in *Blog → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.items[].post
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    post: prismicT.RelationField<"post">;
}
/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Blog`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BlogSliceDefaultPrimary>, Simplify<BlogSliceDefaultItem>>;
/**
 * Slice variation for *Blog*
 *
 */
type BlogSliceVariation = BlogSliceDefault;
/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: `Blog`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSlice = prismicT.SharedSlice<"blog", BlogSliceVariation>;
/**
 * Primary content in Customers → Primary
 *
 */
interface TestimonialsSliceDefaultPrimary {
    /**
     * Title field in *Customers → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in Customers → Items
 *
 */
export interface TestimonialsSliceDefaultItem {
    /**
     * testimonial field in *Customers → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].testimonial
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    testimonial: prismicT.RelationField<"testimonial">;
}
/**
 * Default variation for Customers Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TestimonialsSliceDefaultPrimary>, Simplify<TestimonialsSliceDefaultItem>>;
/**
 * Slice variation for *Customers*
 *
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;
/**
 * Customers Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSlice = prismicT.SharedSlice<"testimonials", TestimonialsSliceVariation>;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSliceDefaultPrimary {
    /**
     * Logo field in *Footer → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Right field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.right
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    right: prismicT.RichTextField;
    /**
     * Legal field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.legal
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    legal: prismicT.RichTextField;
    /**
     * Made by field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.made_by
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    made_by: prismicT.RichTextField;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSliceVariation = FooterSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSlice = prismicT.SharedSlice<"footer", FooterSliceVariation>;
/**
 * Primary content in Header → Primary
 *
 */
interface HeaderSliceDefaultPrimary {
    /**
     * Logo field in *Header → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * CTA field in *Header → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: header.primary.cta
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta: prismicT.RelationField<"cta">;
}
/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Header*
 *
 */
type HeaderSliceVariation = HeaderSliceDefault;
/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSlice = prismicT.SharedSlice<"header", HeaderSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Hero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.TitleField;
    /**
     * Card body field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.card_body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    card_body: prismicT.RichTextField;
    /**
     * Card CTA field in *Hero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.card_cta
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    card_cta: prismicT.RelationField<"cta">;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceDefaultItem {
    /**
     * Image field in *Hero → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, Simplify<HeroSliceDefaultItem>>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Item in Map → Items
 *
 */
export interface MapSliceDefaultItem {
    /**
     * Item field in *Map → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: map.items[].item
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    item: prismicT.RelationField<"mapitem">;
}
/**
 * Default variation for Map Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Map`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MapSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<MapSliceDefaultItem>>;
/**
 * Slice variation for *Map*
 *
 */
type MapSliceVariation = MapSliceDefault;
/**
 * Map Shared Slice
 *
 * - **API ID**: `map`
 * - **Description**: `Map`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MapSlice = prismicT.SharedSlice<"map", MapSliceVariation>;
/**
 * Item in Nav → Items
 *
 */
export interface NavSliceDefaultItem {
    /**
     * Item field in *Nav → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: nav.items[].item
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    item: prismicT.RelationField<"navitem">;
}
/**
 * Default variation for Nav Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Nav`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<NavSliceDefaultItem>>;
/**
 * Slice variation for *Nav*
 *
 */
type NavSliceVariation = NavSliceDefault;
/**
 * Nav Shared Slice
 *
 * - **API ID**: `nav`
 * - **Description**: `Nav`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavSlice = prismicT.SharedSlice<"nav", NavSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CtaDocumentData, CtaDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, MapitemDocumentData, MapitemDocumentDataListItem, MapitemDocument, NavitemDocumentData, NavitemDocumentDataSubitemItem, NavitemDocument, PostDocumentData, PostDocument, TestimonialDocumentData, TestimonialDocument, AllDocumentTypes, BlogSliceDefaultPrimary, BlogSliceDefaultItem, BlogSliceDefault, BlogSliceVariation, BlogSlice, TestimonialsSliceDefaultPrimary, TestimonialsSliceDefaultItem, TestimonialsSliceDefault, TestimonialsSliceVariation, TestimonialsSlice, FooterSliceDefaultPrimary, FooterSliceDefault, FooterSliceVariation, FooterSlice, HeaderSliceDefaultPrimary, HeaderSliceDefault, HeaderSliceVariation, HeaderSlice, HeroSliceDefaultPrimary, HeroSliceDefaultItem, HeroSliceDefault, HeroSliceVariation, HeroSlice, MapSliceDefaultItem, MapSliceDefault, MapSliceVariation, MapSlice, NavSliceDefaultItem, NavSliceDefault, NavSliceVariation, NavSlice };
    }
}
