// Code generated by Slice Machine. DO NOT EDIT.

import Blog from './Blog';
import Footer from './Footer';
import Header from './Header';
import Hero from './Hero';
import MapCategory from './MapCategory';
import Testimonials from './Testimonials';

export {
	Blog,
	Footer,
	Header,
	Hero,
	MapCategory,
	Testimonials,
};

export const components = {
	blog: Blog,
	footer: Footer,
	header: Header,
	hero: Hero,
	map_category: MapCategory,
	testimonials: Testimonials,
};
