// Code generated by Slice Machine. DO NOT EDIT.

import Blog from './Blog';
import Customers from './Customers';
import Footer from './Footer';
import Header from './Header';
import Hero from './Hero';
import Map from './Map';
import Nav from './Nav';

export {
	Blog,
	Customers,
	Footer,
	Header,
	Hero,
	Map,
	Nav,
};

export const components = {
	blog: Blog,
	testimonials: Customers,
	footer: Footer,
	header: Header,
	hero: Hero,
	map: Map,
	nav: Nav,
};
