// Code generated by Slice Machine. DO NOT EDIT.

import Blog from './Blog';
import Customers from './Customers';
import Footer from './Footer';
import Header from './Header';
import Hero from './Hero';

export {
	Blog,
	Customers,
	Footer,
	Header,
	Hero,
};

export const components = {
	blog: Blog,
	testimonials: Customers,
	footer: Footer,
	header: Header,
	hero: Hero,
};
